# This file is designed for production server deployment, not local development work
# For a containerized local dev environment, see: https://github.com/mastodon/mastodon/blob/main/docs/DEVELOPMENT.md#docker

services:
  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image:  tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
    ports:
      - "172.17.0.1:3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/system:/mastodon/public/system

streaming:
    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    # build:
    #   dockerfile: ./streaming/Dockerfile
    #   context: .
    image: tateisu/m1j-streaming:production
    restart: always
    env_file: .env.production
    command: node ./streaming/index.js
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    ports:
      - "172.17.0.1:4000:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro      

  sidekiq_pull:
    # You can uncomment the following line if you want to not use the prebuilt image, for example if you have local code changes
    # build: .
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-pull.yml:/mastodon/config/sidekiq.yml:ro
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 7' || false"]

  sidekiq_push:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-push.yml:/mastodon/config/sidekiq.yml:ro
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  sidekiq_default:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-default.yml:/mastodon/config/sidekiq.yml:ro
    healthcheck:
       test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_hidden_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network
