version: '3'
services:

  web:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - "172.17.0.1:3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs

  streaming:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: node ./streaming
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - "172.17.0.1:4000:4000"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  sidekiq_pull:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-pull.yml:/mastodon/config/sidekiq.yml:ro

  sidekiq_push:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-push.yml:/mastodon/config/sidekiq.yml:ro

  sidekiq_default:
    image: tateisu/m1j:production
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-default.yml:/mastodon/config/sidekiq.yml:ro
