version: '3'
services:


  db_backend:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - /mnt/hdd/mastodon/postgres:/var/lib/postgresql/data

  db:
    restart: always
    image: gavinmroy/alpine-pgbouncer:1.7.2
    volumes:
      - /mnt/hdd/mastodon/pgbouncer:/etc/pgbouncer
    ports:
      - "172.17.0.1:5432:5432"
    depends_on:
      - db_backend

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - /mnt/hdd/mastodon/redis:/data

  web:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "172.17.0.1:3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hdd/mastodon/etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - /mnt/hdd/mastodon/public/assets:/mastodon/public/assets
      - /mnt/hdd/mastodon/public/system:/mastodon/public/system
      - /mnt/hdd/mastodon/public/packs:/mastodon/public/packs
      - /mnt/hdd/mastodon/public/500.html:/mastodon/public/500.html
   
  streaming:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    ports:
      - "172.17.0.1:4000:4000"
    depends_on:
      - db
      - redis


  sidekiq_mailers:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-mailer.yml:/mastodon/config/sidekiq.yml:ro
      
  sidekiq_push:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-push.yml:/mastodon/config/sidekiq.yml:ro

  sidekiq_default:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq 
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-default.yml:/mastodon/config/sidekiq.yml:ro
