version: '3'
services:


  db_backend:
    restart: always
    image: postgres:9.6-alpine
    networks:
      - internal_network
    volumes:
      - ../postgres:/var/lib/postgresql/data

  db:
    restart: always
    image: gavinmroy/alpine-pgbouncer:1.7.2
    networks:
      - internal_network
    volumes:
      - ../pgbouncer:/etc/pgbouncer
    depends_on:
      - db_backend
## expose port for munin
    ports:
      - "172.17.0.1:5432:5432"

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ../redis:/data
    networks:
      - internal_network

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - internal_network
#### Uncomment to enable ES persistance
##    volumes:
##      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - external_network
      - internal_network
    ports:
      - "172.17.0.1:3000:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
   
  streaming:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    ports:
      - "172.17.0.1:4000:4000"
    depends_on:
      - db
      - redis


  sidekiq_mailers:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-mailer.yml:/mastodon/config/sidekiq.yml:ro
      
  sidekiq_push:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-push.yml:/mastodon/config/sidekiq.yml:ro

  sidekiq_default:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq 
    networks:
      - external_network
      - internal_network
    depends_on:
      - db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../etc-ImageMagick-7:/etc/ImageMagick-7:ro
      - ../public/assets:/mastodon/public/assets
      - ../public/system:/mastodon/public/system
      - ../public/packs:/mastodon/public/packs
      - ./config/sidekiq-default.yml:/mastodon/config/sidekiq.yml:ro

networks:
  external_network:
  internal_network:
# for access from munin
# internal: true
