---
:concurrency: 20
:queues:
  - [push, 4]
  - [mailers, 1]
:schedule:
  scheduled_statuses_scheduler:
    every: '5m'
    class: Scheduler::ScheduledStatusesScheduler
  trending_tags_scheduler:
    every: '5m'
    class: Scheduler::TrendingTagsScheduler
  media_cleanup_scheduler:
    cron: '0 12 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 15 * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '1 11 * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '4 5 * * *'
    class: Scheduler::UserCleanupScheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(10..12) %> * * *'
    class: Scheduler::IpCleanupScheduler
  email_scheduler:
    cron: '0 10 * * 2'
    class: Scheduler::EmailScheduler
  backup_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *'
    class: Scheduler::BackupCleanupScheduler
  pghero_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::PgheroScheduler
